# Generated by Django 3.2.4 on 2021-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewStudent',
        ),
        migrations.DeleteModel(
            name='OtherRegister',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentRegister',
        ),
    ]
